AllCops:
  Exclude:
    - 'Rakefile*'
    - 'bin/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

# Barfing on spec blocks

Metrics/BlockLength:
  Enabled: false

# Prefer explicit returns

Style/RedundantReturn:
  Enabled: false

# Prefer lighter and fluffier code

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false
